# -*- coding: utf-8 -*-
"""Buffon Meedle Algorithm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TGBWD1Fg12JKK9q9PLn2n3sx1IyF03Rf
"""

import random
import math

print("Masukkan N : ", end="")
N = int(input())
print("Masukkan l : ", end="")
l = int(input())
print("Masukkan d : ", end="")
d = int(input())
Q = 0

x = [random.uniform(0,d) for i in range(N)]
teta = [random.uniform(0,180/2) for i in range(N)]

for i in range(N):
  if x[i] <= l * math.cos(math.radians(teta[i])):
    Q += 1

print("Total Q : ", Q)

phi = (2*l/d) * (N/Q)
print(phi)